---
- name: Add the OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: 'Ensure EPEL installed'
  yum: pkg=epel-release state=installed
- name: 'Ensure Python PIP installed'
  yum: pkg={{ ssh_aws_pip_version }} state=installed
- name: 'Ensure AWS CLI installed'
  pip: name=awscli state=present

# Move files
- name: sshd configuration file update
  template:
    src=templates/sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - "sshd changed"
- name: copy import_user.sh
  copy:
    src: files/import_users.sh
    dest: "{{ ssh_aws_import_user_path }}"
    owner: root
    group: root
    mode: 0755
- name: copy AuthorizedKeysCommand script
  copy:
    src: files/authorized_key_command.sh
    dest: "{{ ssh_aws_authkey_command_path }}"
    owner: root
    group: root
    mode: 0755
- name: import_users cron
  cron:
    name: import_users cron
    minute: "*/5"
    user: root
    job: "{{ ssh_aws_import_user_path }}"
    cron_file: import_users
    state: present
  notify:
  - "sync users"
